# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Person.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cPerson.proto\x12\x08protobuf\"^\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04locX\x18\x02 \x01(\x05\x12\x0c\n\x04locY\x18\x03 \x01(\x05\x12\x0c\n\x04numP\x18\x04 \x01(\x05\x12\r\n\x05\x64\x65stX\x18\x05 \x01(\x05\x12\r\n\x05\x64\x65stY\x18\x06 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Person_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=26
  _PERSON._serialized_end=120
# @@protoc_insertion_point(module_scope)
